---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts/{post_id}/comments":
    post:
      summary: create comment
      tags:
      - Comments
      parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: comment created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
    get:
      summary: list comments
      tags:
      - Comments
      parameters:
      - name: post_id
        in: path
        description: post_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: comments found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    post_id:
                      type: integer
                    text:
                      type: string
                    author_id:
                      type: integer
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
  "/api/v1/users/{user_id}/posts":
    get:
      summary: list posts
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: posts found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    text:
                      type: string
                    comments_counter:
                      type: integer
                    likes_counter:
                      type: integer
                    author_id:
                      type: integer
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
